Update repo to include R2022b, Introduce new dockerfile for ubuntu:22.04 Pin all other Dockerfiles to Ubuntu:20.04

diff --git a/matlab/Dockerfile.ubuntu-22.04 b/matlab/Dockerfile.ubuntu-22.04
--- a/matlab/Dockerfile.ubuntu-22.04
+++ b/matlab/Dockerfile.ubuntu-22.04
@@ -1,8 +1,8 @@
-# Copyright 2021-2022 The MathWorks, Inc.
+# Copyright 2022 The MathWorks, Inc.
 # Builds Docker image with 
 # 1. MATLAB - Using MPM
 # 2. MATLAB Integration for Jupyter
-# on a base image of jupyter/base-notebook.
+# on a base image of jupyter/base-notebook:ubuntu-22.04
 
 ## Sample Build Command:
 # docker build --build-arg MATLAB_RELEASE=r2022b \
@@ -26,10 +26,10 @@ ARG SHOULD_USE_LICENSE_SERVER=${LICENSE_SERVER:+"_with_lm"}
 ARG MW_CONTEXT_TAGS=MATLAB_PROXY:JUPYTER:MPM:V1
 
 # Base Jupyter image without LICENSE_SERVER
-FROM jupyter/base-notebook:ubuntu-20.04 AS base_jupyter_image
+FROM jupyter/base-notebook:ubuntu-22.04 AS base_jupyter_image
 
 # Base Jupyter image with LICENSE_SERVER
-FROM jupyter/base-notebook:ubuntu-20.04 AS base_jupyter_image_with_lm
+FROM jupyter/base-notebook:ubuntu-22.04 AS base_jupyter_image_with_lm
 ARG LICENSE_SERVER
 # If license server information is available, then use it to set environment variable
 ENV MLM_LICENSE_FILE=${LICENSE_SERVER}
@@ -44,7 +44,7 @@ ARG MATLAB_PRODUCT_LIST
 USER root
 ENV DEBIAN_FRONTEND="noninteractive" TZ="Etc/UTC"
 
-## Installing Dependencies for Ubuntu 20.04
+## Installing Dependencies for Ubuntu 20.04, should largely work for Ubuntu 22.04
 # For MATLAB : Get base-dependencies.txt from matlab-deps repository on GitHub
 # For mpm : wget, unzip, ca-certificates
 # For MATLAB Integration for Jupyter : xvfb
@@ -52,17 +52,33 @@ ENV DEBIAN_FRONTEND="noninteractive" TZ="Etc/UTC"
 ARG MATLAB_DEPS_REQUIREMENTS_FILE="https://raw.githubusercontent.com/mathworks-ref-arch/container-images/main/matlab-deps/${MATLAB_RELEASE}/ubuntu20.04/base-dependencies.txt"
 ARG MATLAB_DEPS_REQUIREMENTS_FILE_NAME="matlab-deps-${MATLAB_RELEASE}-base-dependencies.txt"
 
-# Install dependencies
+## Install dependencies
+## MATLAB versions older than 22b need libpython3.9 which is only present in the deadsnakes PPA on ubuntu:22.04
 RUN wget ${MATLAB_DEPS_REQUIREMENTS_FILE} -O ${MATLAB_DEPS_REQUIREMENTS_FILE_NAME} \
-    && export DEBIAN_FRONTEND=noninteractive && apt-get update \
+    && apt-get update \
+    && export isJammy=`cat /etc/lsb-release | grep DISTRIB_RELEASE=22.04 | wc -l` \
+    && export needsPy39=`cat ${MATLAB_DEPS_REQUIREMENTS_FILE_NAME} | grep libpython3.9 | wc -l` \
+    && if [[ isJammy -eq 1 && needsPy39 -eq 1 ]] ; then apt-get install -y software-properties-common && add-apt-repository ppa:deadsnakes/ppa ; fi \
     && xargs -a ${MATLAB_DEPS_REQUIREMENTS_FILE_NAME} -r apt-get install --no-install-recommends -y \
-    wget \
     unzip \
     ca-certificates \
     xvfb \
     && apt-get clean \
     && apt-get -y autoremove \
     && rm -rf /var/lib/apt/lists/* ${MATLAB_DEPS_REQUIREMENTS_FILE_NAME}
+
+# Note on glibc patch - See https://github.com/mathworks/build-glibc-bz-19329-patch
+# Installation is skipped on Ubuntu 22.04 (Jammy) as it already contains the glibc fix
+
+# Optional: Install MATLAB Engine for Python, if possible. 
+# Note: Failure to install does not stop the build.
+RUN apt-get update \
+    && apt-get install --no-install-recommends -y  python3-distutils \
+    && apt-get clean \
+    && apt-get -y autoremove \
+    && rm -rf /var/lib/apt/lists/* \
+    && cd /opt/matlab/extern/engines/python \
+    && python setup.py install || true
 
 # Run mpm to install MATLAB in the target location and delete the mpm installation afterwards
 RUN wget -q https://www.mathworks.com/mpm/glnxa64/mpm && \ 
@@ -73,28 +89,6 @@ RUN wget -q https://www.mathworks.com/mpm/glnxa64/mpm && \
     --products ${MATLAB_PRODUCT_LIST} && \
     rm -f mpm /tmp/mathworks_root.log && \
     ln -s /opt/matlab/bin/matlab /usr/local/bin/matlab
-
-# Install patched glibc - See https://github.com/mathworks/build-glibc-bz-19329-patch
-WORKDIR /packages
-RUN export DEBIAN_FRONTEND=noninteractive && \
-    apt-get update && apt-get clean && apt-get autoremove && \
-    wget -q https://github.com/mathworks/build-glibc-bz-19329-patch/releases/download/ubuntu-focal/all-packages.tar.gz && \
-    tar -x -f all-packages.tar.gz \
-    --exclude glibc-*.deb \
-    --exclude libc6-dbg*.deb && \
-    apt-get install --yes --no-install-recommends --allow-downgrades ./*.deb && \
-    rm -fr /packages
-WORKDIR /
-
-# Optional: Install MATLAB Engine for Python, if possible. 
-# Note: Failure to install does not stop the build.
-RUN export DEBIAN_FRONTEND=noninteractive && apt-get update \
-    && apt-get install --no-install-recommends -y  python3-distutils \
-    && apt-get clean \
-    && apt-get -y autoremove \
-    && rm -rf /var/lib/apt/lists/* \
-    && cd /opt/matlab/extern/engines/python \
-    && python setup.py install || true
 
 # Switch back to notebook user
 USER $NB_USER
