user can update BASE_ML_INSTALL_LOC arg with their MATLAB install location if its not on the path

diff --git a/matlab-vnc/Dockerfile b/matlab-vnc/Dockerfile
--- a/matlab-vnc/Dockerfile
+++ b/matlab-vnc/Dockerfile
@@ -15,7 +15,10 @@ RUN export ML_INSTALL_LOC=$(which matlab) \
         ML_INSTALL_LOC=$(dirname $(dirname $(readlink -f ${ML_INSTALL_LOC}))); \
         echo "soft linking: " $ML_INSTALL_LOC " to" ${BASE_ML_INSTALL_LOC}; \
         ln -s ${ML_INSTALL_LOC} ${BASE_ML_INSTALL_LOC}; \
-    else echo "MATLAB was not found in your image."; exit 1; \
+    elif [ $BASE_ML_INSTALL_LOC = '/tmp/matlab-install-location' ]; then \
+        echo "MATLAB was not found in your image."; exit 1; \
+    else \
+        echo "Proceeding with user provided path to MATLAB installation: ${BASE_ML_INSTALL_LOC}"; \
     fi
 
 FROM jupyter/base-notebook
diff --git a/matlab/Dockerfile b/matlab/Dockerfile
--- a/matlab/Dockerfile
+++ b/matlab/Dockerfile
@@ -1,7 +1,7 @@
 # Copyright 2020 The MathWorks, Inc.
 
 # Argument shared across multi-stage build to hold location of installed MATLAB 
-ARG BASE_ML_INSTALL_LOC=/tmp/matlab-install-location
+ARG BASE_ML_INSTALL_LOC=/tmp/matlab-install-location3
 
 # Replace "matlab" with the Docker image that contains MATLAB
 # MATLAB should be available on the path in the Docker image
@@ -15,7 +15,10 @@ RUN export ML_INSTALL_LOC=$(which matlab) \
         ML_INSTALL_LOC=$(dirname $(dirname $(readlink -f ${ML_INSTALL_LOC}))); \
         echo "soft linking: " $ML_INSTALL_LOC " to" ${BASE_ML_INSTALL_LOC}; \
         ln -s ${ML_INSTALL_LOC} ${BASE_ML_INSTALL_LOC}; \
-    else echo "MATLAB was not found in your image."; exit 1; \
+    elif [ $BASE_ML_INSTALL_LOC = '/tmp/matlab-install-location' ]; then \
+        echo "MATLAB was not found in your image."; exit 1; \
+    else \
+        echo "Proceeding with user provided path to MATLAB installation: ${BASE_ML_INSTALL_LOC}"; \
     fi
 
 FROM jupyter/base-notebook
