Auto-Locate MATLAB from base image & minor cleanup to increase uniformity

diff --git a/matlab-vnc/Dockerfile b/matlab-vnc/Dockerfile
--- a/matlab-vnc/Dockerfile
+++ b/matlab-vnc/Dockerfile
@@ -1,16 +1,31 @@
 # Copyright 2020 The MathWorks, Inc.
 
-# Replace "matlab:r2020b" with the Docker image that contains MATLAB
-# MATLAB should be installed at /usr/local/MATLAB or other changes will need
-# to be made to this Dockerfile
-FROM matlab:r2020b AS matlab-install-stage
+# Argument shared across multi-stage build to hold location of installed MATLAB 
+ARG BASE_ML_INSTALL_LOC=/tmp/matlab-install-location
+
+# Replace "matlab" with the Docker image that contains MATLAB
+# MATLAB should be available on the path in the Docker image
+FROM matlab AS matlab-install-stage
+ARG BASE_ML_INSTALL_LOC
+
+# Run code to locate a MATLAB install in the base image and softlink
+# to BASE_ML_INSTALL_LOC for a latter stage to copy 
+RUN export ML_INSTALL_LOC=$(which matlab) \
+    && if [ ! -z "$ML_INSTALL_LOC" ]; then \
+        ML_INSTALL_LOC=$(dirname $(dirname $(readlink -f ${ML_INSTALL_LOC}))); \
+        echo "soft linking: " $ML_INSTALL_LOC " to" ${BASE_ML_INSTALL_LOC}; \
+        ln -s ${ML_INSTALL_LOC} ${BASE_ML_INSTALL_LOC}; \
+    else echo "MATLAB was not found in your image."; exit 1; \
+    fi
 
 FROM jupyter/base-notebook
+ARG BASE_ML_INSTALL_LOC
 
+# Switch to root user
 USER root
 
 # Copy MATLAB install from Docker image
-COPY --from=matlab-install-stage /usr/local/MATLAB /usr/local/MATLAB
+COPY --from=matlab-install-stage ${BASE_ML_INSTALL_LOC} /usr/local/MATLAB
 
 # Add MATLAB to the path
 RUN ln -s /usr/local/MATLAB/bin/matlab /usr/local/bin/matlab
